version: "3"

services:

  pdns-recursor:
    image: tmuncks/pdns-recursor:latest
    restart: always
    ports:
      - 53:53/udp
      - 53:53/tcp
    environment:
      - PDNS_any-to-tcp=yes
      - PDNS_dnssec=validate
      - PDNS_reuseport=yes
    volumes:
      - /etc/localtime:/etc/localtime:ro

